name: CI & CD

on:
  push:
    branches:
      - main

env:
  SECRETS_MANAGER_ACCESS_TOKEN: ${{ secrets.SECRETS_MANAGER_ACCESS_TOKEN }}
  MAVEN_ARTIFACTORY: ${{ secrets.MAVEN_ARTIFACTORY }}
  MAVEN_ARTIFACTORY_USERNAME: ${{ secrets.MAVEN_ARTIFACTORY_USERNAME }}
  MAVEN_ARTIFACTORY_PASSWORD: ${{ secrets.MAVEN_ARTIFACTORY_PASSWORD }}

jobs:
  ci:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Prepare Gradle configuration
        run: |
          echo "github.artifactory.url=$MAVEN_ARTIFACTORY" >> gradle.properties
          echo "github.artifactory.username=$MAVEN_ARTIFACTORY_USERNAME" >> gradle.properties
          echo "github.artifactory.password=$MAVEN_ARTIFACTORY_PASSWORD" >> gradle.properties
      - name: Run tests
        run: |
          mkdir bin
          cd bin
          curl -LO https://github.com/bitwarden/sdk/releases/download/bws-v0.3.0/bws-x86_64-unknown-linux-gnu-0.3.0.zip
          unzip bws-x86_64-unknown-linux-gnu-0.3.0.zip
          chmod +x bws
          export PATH=$PATH:$PWD
          cd ../
          ./gradlew test
  cd:
    needs: ci
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Prepare Gradle configuration
        run: |
          echo "github.artifactory.url=\"$MAVEN_ARTIFACTORY\"" >> gradle.properties
          echo "github.artifactory.username=\"MAVEN_ARTIFACTORY_USERNAME\"" >> gradle.properties
          echo "github.artifactory.password=\"MAVEN_ARTIFACTORY_PASSWORD\"" >> gradle.properties
      - name: Publish package
        run: |
          ./gradlew publish